/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialised, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103xb.h"
// #include "cmsis_gcc.h"/*for __disable/enable_irq()*/
// #include "core_cm3.h" /*for NVIC_enableIRQ() and NVIC_SetPriority()*/


#include "event_queue.h"
#include "hc-sr501pir_sensor.h"
#include "usart.h"
#include "esp8266_Firebase.h"
#include "esp8266_WiFi.h" //for testing usart1...
#include "timers.h"
#include "common.h"
#include "i2c.h"
#include "clock.h"
#include "system_control.h"
#include "configurations.h"


/*FOR TESTING*/
//#include "gpio_signal.h" /*for testing*/
/*FOR TESTING*/


int main(void)
{
	//set_sys_clock_to_32MHz();
	//init_MCO();

	USART2_init(); // for debugging

//	init_queue();
//	init_sensor_with_interrupt(); // sensor interrupts are not inabled
//
//	TIMER2_init(); // for monitoring switch state.
//	TIMER3_init(); // for sensor delay
	TIMER4_init(); // for ESP8266 timeout

	USART1_init(); // for ESP8266


	//init_i2c1();
	USART2_write((uint8_t*)("\r\n_______________\r\n"));//For test


	//enable_sensor(); // FOR TESTING

	while(1)
	{

		USART2_write((uint8_t*)("\r\n_______________\r\n"));//For test

	 	USART2_write((uint8_t*)("\r\nWord to the wise: if at some point nothing seems to be happening"));
	 	USART2_write((uint8_t*)("\r\nplease disconnect the device from your computer, wait a few minutes, and then reconnect.\r\n"));


		if(!SYSTEM_CONTROL_set_up()){
		 	USART2_write((uint8_t*)("\r\nWe are sorry, but there seems to be a problem."));
		 	USART2_write((uint8_t*)("\r\nIf you are sure you entered the correct network ssid and password\r\nplease do the following:"));
		 	USART2_write((uint8_t*)("\r\nCheck your network's signal, is it strong enough?"));
		 	USART2_write((uint8_t*)("\r\nIf it is not, please try again later."));
		 	USART2_write((uint8_t*)("\r\nIf it is, please hit the reset button/disconnect your device from the computer, wait a few minutes, then reconnect and try again."));
		 	while(1);
		}

 		USART2_write((uint8_t*)("\r\nHooray, your device was successfully registered."));
 		USART2_write((uint8_t*)("\r\nThis is your device ID: '"));
 		USART2_write(device_id);
 		USART2_write((uint8_t*)("'\r\nPlease coppy it, you will need it later."));
 		USART2_write((uint8_t*)"\r\nIf you ever wish to reset your network details, all you need to do is,\r\nopen 'TeraTerm' on a coputer and cunnect your device.");
 		USART2_write((uint8_t*)("\r\n\r\nYou can now safely remove the  your device and connect it to an electric power supply."));



//		do_event();
//		SYSTEM_CONTROL_monitor_switch_state(120); // every 2 minutes

	}
}
